### ISSUE TITLE
Ne fonctionne pas sous Debian Wheezy

### ISSUE THREAD

**Issue by LeOSW42** [M5oul/coquelicot_ynh#1]
Salut,

Après avoir installé ton app, j'ai une erreur "502 Bad Gateway" qui m'empêche de l'utiliser.

> 2015/06/22 10:12:29 [error] 6143#0: *32062 connect() failed (111: Connection refused) while connecting to upstream, client: 162.38.30.18, server: admin.lstronic.com, request: "GET /coquelicot/ HTTP/1.1", upstream: "http://127.0.0.1:51161//", host: "admin.lstronic.com", referrer: "https://admin.lstronic.com/yunohost/sso/"

Léo

**Comment by LeOSW42** [comment]
Il semble qu'en fait sur wheezy ça coquelicot ne s'installe pas, même en activant les backports.

**Comment by M5oul** [comment]
Il me semble que je  l’ai testé uniquement sur Jessie.

**Comment by LeOSW42** [comment]
Le soucis était bien celui-ci.

**Comment by M5oul** [comment]
https://github.com/M5oul/coquelicot_ynh/commit/35b978bca4873f697162e123262ba2ca490682ec.
